export const FETCH_USER_AUTHENTICATION = 'user/COMMAND/FETCH_USER_AUTHENTICATION';
export const SET_USER_AUTHENTICATION = 'user/COMMAND/SET_USER_AUTHENTICATION';
export const SET_USER_ELIGIBLE = 'user/COMMAND/SET_USER_ELIGIBLE';
export const LOG_OUT = 'user/COMMAND/LOG_OUT';
export const LOGGED_OUT = 'user/EVENT/LOGGED_OUT';
